class AjbDocumentSerializer < ActiveModel::Serializer
  attributes  :id,
              :ajb_number,
              :ppjb_number,
              :customer_id,
              :customer_name,
              :nik,
              :mobile,
              :villa_unit_type,
              :villa_floor_type,
              :villa_price,
              :order_number,
              :booking_fee_status,
              :booking_fee_receipt_url,
              :down_payment_status,
              :down_payment_receipt_url,
              :payment_type,
              :payment_type_status,
              :upload_ajb_doc,
              :ajb_upload_status
end
